# Generated by Django 3.1.7 on 2021-02-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.IntegerField(max_length=200)),
                ('curso', models.IntegerField()),
                ('statura', models.FloatField()),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
