# Generated by Django 3.1.7 on 2021-03-02 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20210301_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='cursos',
            new_name='curso',
        ),
    ]
